# Generated by Django 3.0.2 on 2020-01-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='errors',
            field=models.IntegerField(default=0),
        ),
    ]
