# Generated by Django 3.0.2 on 2020-01-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_text_errors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.CharField(max_length=60)),
                ('correct', models.CharField(max_length=60)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
