# Generated by Django 3.0.2 on 2020-01-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
